# Generated by Django 2.2.4 on 2019-08-15 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('author_id', models.CharField(max_length=100)),
                ('op1_text', models.CharField(max_length=100)),
                ('op2_text', models.CharField(max_length=100)),
                ('op3_text', models.CharField(max_length=100)),
                ('op4_text', models.CharField(max_length=100)),
                ('ans_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title_text', models.CharField(max_length=100)),
                ('author_id', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminTestPapers.Question')),
            ],
        ),
        migrations.CreateModel(
            name='MarksFromTheQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminTestPapers.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminTestPapers.QuestionPaper')),
            ],
        ),
    ]
