# Generated by Django 2.2.4 on 2019-08-16 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminTestPapers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='author_id',
        ),
        migrations.AddField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminTestPapers.TeacherUser'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminTestPapers.TeacherUser'),
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='marksfromthequestion',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminTestPapers.StudentUser'),
        ),
    ]
