# Generated by Django 2.2.4 on 2019-08-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminTestPapers', '0002_auto_20190816_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='question',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='question',
            field=models.ManyToManyField(to='AdminTestPapers.Question'),
        ),
    ]
