# Generated by Django 2.2.4 on 2019-08-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminTestPapers', '0009_auto_20190817_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
