# Generated by Django 2.2.4 on 2019-08-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminTestPapers', '0010_auto_20190817_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='q_paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminTestPapers.QuestionPaper'),
            preserve_default=False,
        ),
    ]
